// function to append answers into html readme elements
function generateReadme(answers) {
    return `
<h1 align="left">${answers.title}</h1>
  
![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />
## 📖 Description
${answers.description}
<br />

## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)
<br />

## ⚒️ Installation
${answers.installation}
<br />

## 🖥️ Usage
${answers.usage}
<br />

## 🏷️ License
![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)
<br />

This application is covered by the ${answers.license} license. 
<br />

## 🙏 Contributing
${answers.contributing}
<br />

## 🧪 Tests
${answers.tests}
<br />

## 💭 Questions
${answers.questions}
<br />

## :octocat: GitHub Username:
[${answers.username}](https://github.com/${answers.username})
<br />

## ✉️ Email me:
[${answers.email}](mailto:${answers.email})
<br />

## 📁 GitHub project repo:
[${answers.projectRepoLink}](${answers.projectRepoLink})
<br />

## 🔗 Deployed application:
[${answers.projectWebPageLink}](${answers.projectWebPageLink})
<br />

<br /><br />
🪄 This README was generated by[ ${answers.username}'s README-generator](https://github.com/FAC-73/dream-attack)
    `;
  }
  
  module.exports = generateReadme;